### ISSUE TITLE
f-slash for non-existent directories

### ISSUE THREAD

**Issue by genovese** [rejeep/f.el#29]
This is a terrific and useful package, thanks.

There are times when I need to manipulate directory names that do not (yet) exist. But f-slash, and thus f-full, do not append the slash in this case. I'm not sure whether f-slash should have the requirement of an existing directory. I think I prefer that it not, but I can see arguments both ways. However, if there is that requirement, I think it should be made clear in the documentation.

If the existence requirement is kept for f-slash, it might be a nice alternative to allow an optional argument to force the behavior:

    (defun f-slash (path &optional if-not-exists)
      "Append slash to PATH unless one is already present.
    A slash will not be appended for a non-existent directory path
    unless IF-NOT-EXISTS is non-nil. Some functions, such as
     `call-process' requires there to be an ending slash."
      (if (or (f-dir? path) if-not-exists)
          (file-name-as-directory path)
        path))

This could be propagated to f-full  (e.g., ``as-directory``) which is the only function calling f-slash.  I see that you need the requirement for f-full so that it can distinguish an arbitrary path as file or directory. However, it seems to me that that is where the requirement belongs rather than in f-slash, which by name just adds a slash.  (UPDATED)

 One could, of course, just call file-name-as-directory in this case, but we might as
well keep the advantage of a unified interface.

**Comment by nikitazu** [comment]
Hi, may I propose slightly another way to do it?

There is a use-case when you need to call `(f-ancestor-of? "/foo10" "/foo100/bar")`.
In such a case it does not matter whether `foo10` is a file or a directory, it can not be an ancestor of `foo100` anyway, it is a completely different path, that just matches since we're comparing two strings. Forcefully adding a slash at the end will fix it. But since passing optional arguments from `f-ancestor-of?` or `f-descendant-of?` to `f-full` and then to `f-slash` is not a good design, it is possible to just introduce a dynamically scoped variable like `f-slash-force-directory-file-name` and check like:

```
(defvar f-slash-force-directory-file-name nil)

(defun f-slash (path)
  "..."
  (if (or f-slash-force-directory-file-name
           (f-dir? path))
      (file-name-as-directory path)
    path))
```

Then a caller can do it like:
```
(let ((f-slash-force-directory-file-name t)) ;; dynamically overriding f-slash inside of a let form
  (f-ancestor-of? "some-path/1" "some-path/100/file3.txt"))
```

This way the default behaviour would not change at all, but people like me could use such a setting, for very special cases.

**Comment by rejeep** [comment]
I don't like the dynamic variable idea because I think it's bad API. It's hard to document. Instead, I think that f should not require real paths whenever possible. It's better for performance also.

**Comment by rejeep** [comment]
Closing this in favor of #42
