### ISSUE TITLE
wait-timeout for f--collecting-entries

### ISSUE THREAD

**Issue by soonhokong** [rejeep/f.el#45]
Hi,

I found out that `f--collecting-entries` function takes quite a lot of time when it recursively collects entries (where a directory has many entries). I wanted to use `wait-timeout` to wrap `f--collecting-entries` but it doesn't work with the current implementation because `f--collecting-entries` never wait for an input.

My current work-around is to insert `(sit-for 0.000001)` at https://github.com/rejeep/f.el/blob/master/f.el#L425 . I'm wondering whether there is a better solution for my problem. Any suggestion is welcome.

**Comment by rejeep** [comment]
I'm not really sure what you are trying to achieve here, but it seems like it's a little bit out of f.el's scope. The purpose of this library is to create a good API on top of the rather bad builtin one. Simplicity is the main goal, performance not so much.

I think that if you want to do such operations, you should probably shell out and use a callback. A similar approach used by for example Projectile is to ask the VCS for the files that are tracked, which is really fast, but that only works if you are searching in a project of course.

Otherwise I would recommend you to shell out (you can of course use f.el in the shell script) with a callback function when it's done.

Ps, sorry for the late reply.

**Comment by soonhokong** [comment]
I see. Thanks for the comments!
